name: clothing_app
description: "A new Flutter project."

publish_to: "none" # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add image assets
  assets:
    - assets/images/logo.png
    - assets/images/image1.jpg
    - assets/images/image2.jpeg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.png
    - assets/images/image6.jpg
    - assets/images/image7.jpg
    - assets/images/image8.jpg
    - assets/images/image9.jpg
    - assets/images/image10.jpg
    - assets/images/image13.jpg
    - assets/images/image14.jpg
    - assets/images/image15.jpg
    - assets/images/image16.jpg

    - assets/images/Sketch1.png
    - assets/images/Sketch2.png
    - assets/images/Sketch3.png
    - assets/images/Sketch4.png
    - assets/images/Sketch5.png
    - assets/images/image11.png

    - assets/images/google_icon.png

  # Add font assets
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
