name: clothing_app
description: "A new Flutter project."

publish_to: "none" # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  url_launcher: ^6.0.9
  video_player: ^2.3.0

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  flick_video_player: ^0.9.0
  lottie: ^3.3.1
  flutter_colorpicker: ^1.1.0
  flutter_drawing_board: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add image assets
  assets:
    - assets/images/logo.png
    - assets/images/image1.jpg
    - assets/images/image2.jpeg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.png
    - assets/images/image6.jpg
    - assets/images/image7.jpg
    - assets/images/image8.jpg
    - assets/images/image9.jpg
    - assets/images/image10.jpg
    - assets/images/image13.jpg
    - assets/images/image14.jpg
    - assets/images/image15.jpg
    - assets/images/image16.jpg
    - assets/images/image17.jpg
    - assets/images/image19.jpeg
    - assets/images/image21.jpeg
    - assets/images/image23.jpeg
    - assets/images/image24.jpeg
    - assets/images/image25.jpeg
    - assets/images/image26.jpeg
    - assets/images/image27.png
    - assets/images/image30.png
    - assets/images/image32.png
    - assets/images/image33.png
    - assets/images/image35.jpg
    - assets/images/image36.jpg
    - assets/images/image37.jpg
    - assets/images/image38.jpg
    - assets/images/image36.jpg
    - assets/images/image44.jpeg
    - assets/images/image45.jpeg
    - assets/images/cotton.jpg
    - assets/images/velvet.jpg
    - assets/images/jaquard.jpg
    - assets/video1.mp4

    - assets/images/woolknitted.jpg
    - assets/images/Sketch1.jpeg
    - assets/images/Sketch2.jpeg
    - assets/images/Sketch3.jpeg
    - assets/images/Sketch4.jpeg
    - assets/images/Sketch5.jpeg
    - assets/images/Sketch6.jpeg
    - assets/images/Sketch7.jpeg
    - assets/images/Sketch8.jpeg
    - assets/images/Sketch9.jpeg
    - assets/images/Sketch10.jpeg
    - assets/images/Sketch11.jpeg
    - assets/images/Sketch12.jpeg
    - assets/images/Sketch13.jpeg
    - assets/images/Sketch14.jpeg
    - assets/images/Sketch15.jpeg
    - assets/images/image11.png

    - assets/images/google_icon.png
    - assets/animations/Animation2.json
    - assets/animations/Animation1.json
    - assets/animations/Animation6.json
    - assets/animations/Animation7.json
    - assets/animations/Animation8.json
    - assets/animations/Animation4.json
    - assets/animations/Animation5.json
    - assets/animations/Animation9.json
    - assets/animations/Animation10.json
    - assets/animations/Animation11.json
    - assets/animations/Animation12.json
    - assets/animations/Animation15.json

  # Add font assets
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
