name: Deploy Minimal App to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Create deployment package
      run: |
        cd azure-minimal
        npm install --production
        zip -r ../azure-minimal.zip .

    - name: Deploy to Azure Web App
      id: deploy-to-azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'dressme-backend-h5dtc6gcgjbzfkax'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: azure-minimal.zip

    - name: Output deployment URL
      run: echo "Deployed to https://dressme-backend-h5dtc6gcgjbzfkax.westus2-01.azurewebsites.net"
