name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
      - backend-deployment
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create minimal server file
      run: |
        cat > minimal-server.js << EOL
        // Minimal server for Azure deployment
        const http = require('http');
        
        const server = http.createServer((req, res) => {
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({
            status: 'online',
            message: 'DressMe Fashion Design API is running',
            timestamp: new Date().toISOString()
          }));
        });
        
        const PORT = process.env.PORT || 8080;
        server.listen(PORT, () => {
          console.log(`Server running on port ${PORT}`);
        });
        EOL
      
    - name: Create minimal package.json
      run: |
        cat > minimal-package.json << EOL
        {
          "name": "dressme-azure-minimal",
          "version": "1.0.0",
          "main": "minimal-server.js",
          "scripts": {
            "start": "node minimal-server.js"
          },
          "engines": {
            "node": "18.x"
          }
        }
        EOL
      
    - name: Create minimal web.config
      run: |
        cat > minimal-web.config << EOL
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <system.webServer>
            <handlers>
              <add name="iisnode" path="minimal-server.js" verb="*" modules="iisnode" />
            </handlers>
            <rewrite>
              <rules>
                <rule name="DynamicContent">
                  <action type="Rewrite" url="minimal-server.js" />
                </rule>
              </rules>
            </rewrite>
          </system.webServer>
        </configuration>
        EOL
      
    - name: Create deployment package
      run: |
        mkdir -p minimal-deploy
        cp minimal-server.js minimal-deploy/
        cp minimal-package.json minimal-deploy/package.json
        cp minimal-web.config minimal-deploy/web.config
        cd minimal-deploy && zip -r ../minimal-deploy.zip .
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dressme-backend-h5dtc6gcgjbzfkax'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: minimal-deploy.zip
        startup-command: 'node minimal-server.js'
