name: Deploy to Azure (Simple)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Create basic server file
      run: |
        cat > server-basic.js << EOL
        const express = require('express');
        const app = express();
        
        app.get('/', (req, res) => {
          res.json({
            status: 'online',
            message: 'DressMe Fashion Design API is running',
            timestamp: new Date().toISOString()
          });
        });
        
        const PORT = process.env.PORT || 8080;
        app.listen(PORT, () => {
          console.log(`Server running on port ${PORT}`);
        });
        EOL
      
    - name: Create deployment package
      run: |
        mkdir -p deploy-package
        cp server-basic.js deploy-package/
        cp web.config deploy-package/
        cat > deploy-package/package.json << EOL
        {
          "name": "dressme-azure",
          "version": "1.0.0",
          "main": "server-basic.js",
          "scripts": {
            "start": "node server-basic.js"
          },
          "dependencies": {
            "express": "^4.18.2"
          }
        }
        EOL
        cd deploy-package && npm install --production
        cd deploy-package && zip -r ../deploy.zip .
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Deploy to Azure Web App (ZIP Deploy)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dressme-backend-h5dtc6gcgjbzfkax'
        package: deploy.zip
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        slot-name: 'production'
        startup-command: 'node server-basic.js'
